PACK_SCHEMA_VERSION = "1.0"
GENERATOR_VERSION = "0.1.0"

DEFAULT_EXTRACTOR = "pymupdf"
DEFAULT_EMBEDDING_MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"
DEFAULT_EMBEDDING_DIMENSIONS = 384

MANIFEST_FILE = "manifest.json"
DOCUMENTS_FILE = "documents.json"
CHUNKS_FILE = "chunks.jsonl"
EMBEDDINGS_FILE = "embeddings.npy"
EXTRACTION_REPORT_FILE = "extraction-report.json"

REQUIRED_PACK_FILES = {
    MANIFEST_FILE,
    DOCUMENTS_FILE,
    CHUNKS_FILE,
    EMBEDDINGS_FILE,
    EXTRACTION_REPORT_FILE,
}

DEFAULT_MAX_CHARS_PER_CHUNK = 1800
SUSPICIOUS_PAGE_CHAR_THRESHOLD = 40



